### ISSUE TITLE
algpseudocodex

### ISSUE THREAD

**Issue by GMS103** [jandermoreira/algxpar#1]
Hello and thanks for this package.

Would it be possible to use ```algpseudocodex``` instead of ```algpseudocode```?

The doc says:
_Basic usage is identical to ```algpseudocode``` from the ```algorithmicx``` package. Pseudocode
written for that package should also be compatible with ```algpseudocodex```._

One thing I am interested in is the option ```ìndLines```.

**Comment by jandermoreira** [comment]
I didn't know about `algpseudocodex`, so I took a look at its code.
As far as I could see, it is a new implementation for pseudocode and `indLines` is a nice feature!

On the other hand, `algxpar` is an extension to `algpseudocode` and uses its intenal implementation.

Using `algpseudocodex` instead of `algpseudo`  with `algxpar` is unfortunately not possible.

**Comment by GMS103** [comment]
Thanks.  I understood as much when looking at your code.
The main features (for me) of ```algxpar ``` are ```comment width = nice```, even if the value is hardcoded, and the possibilities for customization, even if I had to modify ```algxpar.sty``` (to get for instance **Begin** and **End** at the same level as ```\Description```).
I have not tried ```algpseudocodex``` sufficiently to see what I can get from it, so I have not yet made a choice between the two.

**Comment by jandermoreira** [comment]
`indLines` was a desired feature I just forgot about.

I made some changes to add such a feature to algxpar, but it's not fully tested yet.
If you want, give it a try and please report bugs.

Use:
```
\AlgSet{indent lines}
```

or

```
\AlgSet{indent lines, line style = {blue, dotted}}
```
or

```
\documentclass{article}

\usepackage{algxpar}

\begin{document}

\begin{algorithmic}<
	noend,
	indent lines,
	line style = {very thick, blue!30}
	>
  \State $x \gets 0$
  \ForAll{$x$}
    \State $x \gets -1$
    \State $y \gets -1$
    \State $z \gets -1$
    \If{$x$}
      \State $x \gets -1$
      \State $y \gets -1$
      \State $z \gets -1$
    \EndIf
  \EndFor
\end{algorithmic}

\end{document}
```

Comments are welcome!
